-- MySQL Script generated by MySQL Workbench
-- 05/28/18 16:48:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mystudio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mystudio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mystudio` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mystudio` ;

-- -----------------------------------------------------
-- Table `mystudio`.`STYLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mystudio`.`STYLES` (
  `id_style` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `style_name` VARCHAR(12) NOT NULL COMMENT '',
  PRIMARY KEY (`id_style`)  COMMENT '',
  UNIQUE INDEX `idtable1_UNIQUE` (`id_style` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mystudio`.`ARTISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mystudio`.`ARTISTS` (
  `id_artist` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `artist_name` VARCHAR(25) NOT NULL COMMENT '',
  `category` ENUM('amateur', 'pro') NOT NULL COMMENT '',
  PRIMARY KEY (`id_artist`)  COMMENT '',
  UNIQUE INDEX `id_artist_UNIQUE` (`id_artist` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mystudio`.`ALBUMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mystudio`.`ALBUMS` (
  `id_album` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `album_name` VARCHAR(45) NOT NULL COMMENT '',
  `album_cover` VARCHAR(30) NULL COMMENT '',
  `release_date` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id_album`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mystudio`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mystudio`.`USERS` (
  `id_user` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(15) NOT NULL COMMENT '',
  `pw` VARCHAR(25) NOT NULL COMMENT '',
  `category` ENUM('artiste', 'auditeur') NOT NULL COMMENT '',
  PRIMARY KEY (`id_user`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mystudio`.`MUSICS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mystudio`.`MUSICS` (
  `id_music` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  `featuring` VARCHAR(45) NOT NULL COMMENT '',
  `nb_listening` INT NOT NULL COMMENT '',
  `lyrics` BLOB NULL COMMENT '',
  `trans` BLOB NULL COMMENT '',
  `music` BLOB NULL COMMENT '',
  `style` INT NOT NULL COMMENT '',
  `album` INT NOT NULL COMMENT '',
  `artist` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_music`)  COMMENT '',
  INDEX `artist_idx` (`artist` ASC)  COMMENT '',
  INDEX `style_idx` (`style` ASC)  COMMENT '',
  INDEX `album_idx` (`album` ASC)  COMMENT '',
  CONSTRAINT `album`
    FOREIGN KEY (`album`)
    REFERENCES `mystudio`.`ALBUMS` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `style`
    FOREIGN KEY (`style`)
    REFERENCES `mystudio`.`STYLES` (`id_style`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `artist`
    FOREIGN KEY (`artist`)
    REFERENCES `mystudio`.`ARTISTS` (`id_artist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mystudio`.`PLAYLISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mystudio`.`PLAYLISTS` (
  `id_playlist` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `play_title` VARCHAR(45) NOT NULL COMMENT '',
  `birthdate` DATE NOT NULL COMMENT '',
  `users` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_playlist`)  COMMENT '',
  INDEX `users_idx` (`users` ASC)  COMMENT '',
  CONSTRAINT `users`
    FOREIGN KEY (`users`)
    REFERENCES `mystudio`.`USERS` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mystudio`.`REGISTERED_IN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mystudio`.`REGISTERED_IN` (
  `id_play` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `music` INT NOT NULL COMMENT '',
  `playlist` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_play`)  COMMENT '',
  INDEX `music_idx` (`music` ASC)  COMMENT '',
  CONSTRAINT `music`
    FOREIGN KEY (`music`)
    REFERENCES `mystudio`.`MUSICS` (`id_music`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `playlist`
    FOREIGN KEY (`id_play`)
    REFERENCES `mystudio`.`PLAYLISTS` (`id_playlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mystudio`.`FAV_BY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mystudio`.`FAV_BY` (
  `username` INT NOT NULL COMMENT '',
  `music` INT NOT NULL COMMENT '',
  `id_fav` INT NOT NULL AUTO_INCREMENT COMMENT '',
  INDEX `music_idx` (`music` ASC)  COMMENT '',
  INDEX `username_idx` (`username` ASC)  COMMENT '',
  PRIMARY KEY (`id_fav`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
